export const STATUS_LIST = ['online', 'offline', 'not-login']
export const STATUS_COLOR_LIST = ['#009900', '#ffa500', '#990000']
export type FILTER_NAME = '' | 'Firm' | 'Status' | 'Stage' | 'Lead' | 'Advanced Search' | 'Clear Filters'

export const FIRM_NAMES = [
  '10D',
  '1315 Capital',
  '1flourish Capital',
  '20/20 HealthCare Partners',
  '3M Ventures',
  '3B Future Health Ventures',
  '3H Health Investment',
  '3T Invest',
  '4BIO Capital',
  '4See Ventures',
  '5AM Ventures',
  '6 Dimensions Capital',
  'Fifty Years',
  '415 CAPITAL',
  '1315 Capital',
  'AB Magnitude Ventures Group',
  'Abbey Road Capital',
  'AbbVie Ventures',
  'Abingworth',
  'Able Partners',
  'Accelmed Ventures',
  'Accelerator Life Science Partners',
  'Ackermans & van Haaren',
  'Active Impact Investments',
  'Adara Ventures',
  'AdBio partners',
  'Addition',
  'Aditum Bio',
  'Adjuvant Capital',
  'Adjacent Venture Capital',
  'AFI Capital Partners',
  'Advent Life Sciences',
  'AlbionVC',
  'Aglaia Oncology Funds',
  'Alignment Ventures',
  'Ahren Innovation Capital',
  'Ally Bridge Group',
  'AJU IB Investment',
  'Almeda Ventures',
  'ALSA Ventures',
  'Altitude Ventures',
  'Altitude Life Science Ventures',
  'Altium Capital Management',
  'Amgen Ventures',
  'aMoon Fund',
  'Amplitude Ventures',
  'AMR Action Fund',
  'Amzak Health',
  'Andera Partners',
  'Animatrix Capital',
  'Aphelion Capital',
  'Apollo Health Ventures',
  'Arboretum Ventures',
  'ARCH Venture Partners\n',
  'Arix Bioscience',
  'Arkin Holdings',
  'Artfo Holdings',
  'ARTIS Ventures',
  'Asabys Partners',
  'Asahi Kasei Corporate Venture Capital',
  'ASAJES Ventures',
  'Ascension Ventures',
  'Ascend Venture Capital (Seattle)\n',
  'Astellas Venture Management',
  'August Capital',
  'AV8 Ventures',
  'Avanteca Partners',
  'Avego Management',
  'AXA Investment Managers',
  'Avestria Ventures',
  'Axial (San Francisco)',
  'Bain Capital Life Sciences',
  'Barda Ventures',
  'Barwell',
  'Bay Bridge Ventures',
  'Bandera Partners',
  'Bavarian Capital Management',
  'BASF Venture Capital',
  'Bay City Capital',
  'Baird Capital',
  'B Capital Group',
  'Bioengine Capital',
  'Bioqube Ventures',
  'Bios Partners',
  'Biomatics Capital',
  'Bilgola Capital',
  'Berkeley Catalyst Fund',
  'Bioscience Managers',
  'BioStar Capital',
  'Biobrit',
  'BioMedPartners',
  'Beyond Next Ventures',
  'BioTrack Capital',
  'BioAdvance',
  'Blackbird Ventures',
  'Beringea',
  'Bessemer Venture Partners',
  'Borski Fund',
  'Breakout Ventures',
  'Breakout Labs',
  'Brighteye Ventures',
  'Bonaventure Capital',
  'Borealis Ventures',
  'Boehringer Ingelheim Venture Fund',
  'Boxer Capital',
  'Blackhorn Ventures',
  'Blackstone Life Sciences',
  'Blue Horizon Corporation',
  'bp Ventures',
  'Blumberg Capital',
  'Brightlands Venture Partners',
  'Broadview Ventures',
  'Builders VC',
]

// export const STAGE_LIST = 